apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce-dev
  labels:
    app.kubernetes.io/name: order-service
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: order-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: order-service
    spec:
      containers:
        - name: order-service
          image: ghcr.io/rakib1620/order-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http

          # Zero-Trust Secret Injection via External Secrets Operator
          envFrom:
            - secretRef:
                name: ecommerce-app-secrets

          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
