apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecommerce-app-secrets
  namespace: ecommerce-dev
spec:
  # Automated background secret rotation interval
  refreshInterval: "1h"

  # Reference to our ClusterSecretStore
  secretStoreRef:
    name: aws-secrets-manager-store
    kind: ClusterSecretStore

  # Target native Kubernetes secret created in-memory
  target:
    name: ecommerce-app-secrets
    creationPolicy: Owner

  # Mapping remote AWS Secrets Manager keys to Kubernetes Secret keys
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: ecommerce/dev/database
        property: POSTGRES_DB

    - secretKey: POSTGRES_USER
      remoteRef:
        key: ecommerce/dev/database
        property: POSTGRES_USER

    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: ecommerce/dev/database
        property: POSTGRES_PASSWORD

    - secretKey: DATABASE_URL
      remoteRef:
        key: ecommerce/dev/database
        property: DATABASE_URL

    - secretKey: JWT_SECRET
      remoteRef:
        key: ecommerce/dev/auth
        property: JWT_SECRET

    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: ecommerce/dev/payment
        property: STRIPE_SECRET_KEY
