apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-irsa-sa
  namespace: external-secrets
  annotations:
    # AWS IAM Role mapped via OIDC IRSA provisioned in Phase 4
    eks.amazonaws.com/role-arn: arn:aws:iam::931092012480:role/ecommerce-eks-dev-external-secrets-role
